# This file was generated by GoReleaser. DO NOT EDIT.
cask "omniview-cli" do
  name "omniview-cli"
  desc "CLI tool for the Omniview plugin ecosystem"
  homepage "https://github.com/omniviewdev/omniview-cli"
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "omniview"
  bash_completion "completions/omniview.bash"
  zsh_completion "completions/omniview.zsh"
  fish_completion "completions/omniview.fish"

  on_macos do
    on_intel do
      url "https://github.com/omniviewdev/omniview-cli/releases/download/v#{version}/omniview_#{version}_darwin_amd64.tar.gz"
      sha256 "6060630fb679b5319340a41d24428446d6565aaee2f824c6000e4cedf61d4efb"
    end
    on_arm do
      url "https://github.com/omniviewdev/omniview-cli/releases/download/v#{version}/omniview_#{version}_darwin_arm64.tar.gz"
      sha256 "63b8bfa3a3458a0fb7a9f5c9fd73063ae67ff6d616c5ac9bc8dbbbacff07a8c4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/omniviewdev/omniview-cli/releases/download/v#{version}/omniview_#{version}_linux_amd64.tar.gz"
      sha256 "25225b6440f95edf7a5c0cacb1f370323f59b5cf31c4242eb807256d7553b932"
    end
    on_arm do
      url "https://github.com/omniviewdev/omniview-cli/releases/download/v#{version}/omniview_#{version}_linux_arm64.tar.gz"
      sha256 "5d135d50c53a6093cb228086c802e933eccfc37f81098b79e71a605973a68519"
    end
  end

  # No zap stanza required
end
