# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OmniviewCli < Formula
  desc "CLI tool for the Omniview plugin ecosystem"
  homepage "https://github.com/omniviewdev/omniview-cli"
  version "0.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/omniviewdev/omniview-cli/releases/download/v0.0.1/omniview_0.0.1_darwin_amd64.tar.gz"
      sha256 "d7023610e8d577d5d32da4c89a72bb93ee800e6e94255e81a3c60410fd78f647"

      define_method(:install) do
        bin.install "omniview"
        generate_completions_from_executable(bin/"omniview", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/omniviewdev/omniview-cli/releases/download/v0.0.1/omniview_0.0.1_darwin_arm64.tar.gz"
      sha256 "4f6f073a4c8287c821c334c07d0381b75f519632fbba124b26d00af795e6de24"

      define_method(:install) do
        bin.install "omniview"
        generate_completions_from_executable(bin/"omniview", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/omniviewdev/omniview-cli/releases/download/v0.0.1/omniview_0.0.1_linux_amd64.tar.gz"
      sha256 "f5095322828c1852dea5bca5a3a3d67c6953acf968569eea2fcfc8b1a0221cb6"
      define_method(:install) do
        bin.install "omniview"
        generate_completions_from_executable(bin/"omniview", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/omniviewdev/omniview-cli/releases/download/v0.0.1/omniview_0.0.1_linux_arm64.tar.gz"
      sha256 "d831d34cc73fdd9528c00c9f7fa85887b8c1f324811fc939459126be39eda3d4"
      define_method(:install) do
        bin.install "omniview"
        generate_completions_from_executable(bin/"omniview", "completion")
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/omniview version")
  end
end
